"""empty message

Revision ID: 16df9c21cbc1
Revises: 363ec285cd80
Create Date: 2021-12-18 19:14:45.746938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16df9c21cbc1'
down_revision = '363ec285cd80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('term')
    # ### end Alembic commands ###
