"""empty message

Revision ID: 363ec285cd80
Revises: 
Create Date: 2021-12-17 14:41:06.427859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363ec285cd80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('invite', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'course', ['invite'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='unique')
    op.drop_column('course', 'invite')
    # ### end Alembic commands ###
